### ISSUE TITLE
start.bat error

### ISSUE THREAD

**Issue by 0730gabriel0730** [KSCHdsc/BlackCap-Grabber#140]
Traceback (most recent call last):
  File "builder.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Press any key to continue . . .

**Comment by xirooov2** [comment]
same

**Comment by LuaKingLord** [comment]
> Traceback (most recent call last):
> 
>   File "builder.py", line 11, in <module>
> 
>     import requests
> 
> ModuleNotFoundError: No module named 'requests'
> 
> Press any key to continue . . .



Pip install requests
