### ISSUE TITLE
i keep geting this eror

### ISSUE THREAD

**Issue by danthe0** [KSCHdsc/BlackCap-Grabber#16]
Traceback (most recent call last):
  File "obfuscated_compressed_mod.py", line 21, in <module>
  File "<string>", line 1, in <module>
  File "auoiwhgoawhg", line 15, in <module>
ImportError: DLL load failed while importing win32gui: The specified module could not be found.

**Comment by KSCHdsc** [comment]
Try pip install win32gui in terminal
