### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FeddywapX** [KSCHdsc/BlackCap-Grabber#76]
Traceback (most recent call last):                                                                                        File "C:\Users\casca\OneDrive\Desktop\BlackCap-Grabber-main\builder.py", line 10, in <module>                             import requests                                                                                                       File "C:\Users\casca\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py", line 58, in <module>                                                                                                                        from . import utils                                                                                                   File "C:\Users\casca\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 30, in <module>                                                                                                                           from .cookies import RequestsCookieJar, cookiejar_from_dict                                                           File "C:\Users\casca\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\cookies.py", line 159, in <module>                                                                                                                        class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                             AttributeError: module 'collections' has no attribute 'MutableMapping'                                                  Press any key to continue . . .

**Comment by KSCHdsc** [comment]
can you retry?

**Comment by FeddywapX** [comment]
Yeah I can retry just says same thing over an over again.

**Comment by FeddywapX** [comment]
Fixed it. Looks bad ass!

**Comment by KSCHdsc** [comment]
how?
